Repository peerplays-network/getscatter-walletpack, pull requests merged in 2020-02, with the labels that each got.

#27 Use peerplaysjs-lib where possible. Add tests
  packages/peerplays/__tests__/peerplays.test.js
  packages/peerplays/__tests__/walletpack-core.test.js
  packages/peerplays/lib/peerplays.js
Labels: enhancement

#29 (XL) SC-16 Refactor fetch calls for re-usability.
  packages/peerplays/__tests__/peerplays.test.js
  packages/peerplays/lib/peerplays.js
  packages/peerplays/package.json
Labels: documentation, enhancement

#30 (L) SC-3 Signing Functionality
  packages/peerplays/__tests__/peerplays.test.js
  packages/peerplays/lib/peerplays.js
Labels: documentation, enhancement

#32 SC-5 Peerplays transfer
  packages/peerplays/__tests__/peerplays.test.js
  packages/peerplays/lib/peerplays.js
Labels: documentation, enhancement

#37 Add function to convert human readable num to blockchain num
  packages/peerplays/__tests__/peerplays.test.js
  packages/peerplays/lib/_PPY.js
  packages/peerplays/lib/peerplays.js
Labels: bug

#38 [L] Peerplays one keypair with all WIFs within it
  packages/peerplays/__tests__/peerplays.test.js
  packages/peerplays/lib/PPYKeypairService.js
Labels: dependencies, enhancement

#42 Peerplays transfer updates for ui support
  packages/core/lib/services/blockchain/TransferService.js
  packages/peerplays/__tests__/peerplays.test.js
  packages/peerplays/lib/peerplays.js
Labels: bug

#45 Peerplays Import
  packages/core/lib/services/blockchain/AccountService.js
  packages/core/lib/services/secure/KeyPairService.js
  packages/peerplays/__tests__/walletpack-core.test.js
  packages/peerplays/lib/PPYKeypairService.js
  packages/peerplays/lib/peerplays.js
Labels: bug, enhancement

#49 (L) Update to transfer transaction building, and signing.
  packages/peerplays/__tests__/peerplays.test.js
  packages/peerplays/lib/PPYKeypairService.js
  packages/peerplays/lib/_PPY.js
  packages/peerplays/lib/peerplays.js
Labels: enhancement
